### ISSUE TITLE
Truffle install fails

### ISSUE THREAD

**Issue by markspanbroek** [oraclize/ethereum-api#13]
When I try to install the Oraclize EthPM package in Truffle, I get the following error:

```
Error: Unknown server response 504 when downloading hash QmWrjVJkSUhpBbM7TR4hN1kxiuFjzhvEobEwtLgquaCfPi
    at ClientRequest.<anonymous> (/Users/.../node_modules/truffle/build/cli.bundled.js:132502:16)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
error Command failed with exit code 1.
```

Installing a different package (I tried Zeppelin) does work.
I'm using Truffle version 3.2.8

**Comment by bertani** [comment]
The EthPM package is not up to date with the upstream Oraclize API and it seems like the old IPFS multihash is not being preserved anymore by running nodes. Thanks for reporting the issue, we'll update the package as soon as possible and update this issue accordingly. In the meantime you can download the latest oraclizeAPI.sol from [here](https://github.com/oraclize/ethereum-api/blob/master/oraclizeAPI_0.4.sol).

**Comment by markspanbroek** [comment]
Thanks @bertani for updating the EthPM package. It works like a charm now.
Closing the issue.
